exclude: ['vendor/bundle', 'node_modules', '.git', '.bundle', '.saas-cache', '.bowerrc', '.gitignore', 'Gemfile', 'Gemfile.lock']
title: Jekyll_python Test Site
description: Python Programming Test Site
show_downloads: false
google_analytics: UA-101084548-4
theme: jekyll-theme-architect
